import type { GetStaticProps } from "next";
import Head from "next/head";
import About from "../components/About";
import Contact from "../components/Contact";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import WorkExperience from "../components/WorkExperience";
import Link from "next/link";
import { AboutInfo, ContactsInfo, Experience,HeroInfo, Project, Skill,  Social } from "../typings";
import { fetchExperiences } from "../utils/fetchExperiences";
import { fetchProjects } from "../utils/fetchProjects";
import { fetchSkills } from "../utils/fetchSkills";
import { fetchSocials } from "../utils/fetchSocials";
import { fetchHeroInfo } from "../utils/fetchHeroInfo";
import { fetchAboutInfo } from "../utils/fetchAboutInfo";
import { fetchContactsInfo } from "../utils/fetchContactsInfo";

type Props = {
  
  experiences: Experience[];
  skills: Skill[];
  projects: Project[];
  socials: Social[];
  heroInfo: HeroInfo;
  aboutInfo: AboutInfo;
  contactsInfo: ContactsInfo;
};

const Home = ({experiences,skills,projects,socials,heroInfo,aboutInfo,contactsInfo}:Props) => {
  return (
    <div
      className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory 
    overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80"
    >
      <Head>
        <title>Festus Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header socials={socials} />

      <section id="hero" className="snap-start">
        <Hero {...{heroInfo}} />
      </section>

      <section id="about" className="snap-center">
        <About {...{aboutInfo}}/>
      </section>

      <section id="experience" className="snap-center">
        <WorkExperience {...{experiences}} />
      </section>

      <section id="skills" className="snap-start">
        <Skills {...{skills}}/>
      </section>

      <section id="projects" className="snap-start">
        <Projects {...{projects}} />
      </section>

      <section id="contacts" className="snap-start">
        <Contact {...{contactsInfo}} />
      </section>

      {/* <Link href="#hero">
        <footer className="sticky bottom-5 w-full cursor-pointer">
          <div className="flex items-center justify-center">
            <img
              src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAQEBUREBIQFRUVFRUQExcYEBUYFxYWFRUXFhUVGBcYHSggGBolGxUVITIhJikrLi4uFx8zODMsNygtLisBCgoKDg0OFxAQGi0mICYtLSstKy0tLS0tLy0tLS0tLS0tLS0tLS0tLy0tLS0tKy0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAOYA2wMBIgACEQEDEQH/xAAcAAACAgMBAQAAAAAAAAAAAAAAAwYHAgQFAQj/xABMEAACAgACBQYHDQYEBQUAAAABAgADBBEFBhIhMRNBUWFxgQciMkJSkaEUIzNicnOCsbKzwdHwJDSSk6LCU1SD4Rc1Q2PTFSVE0vH/xAAbAQACAwEBAQAAAAAAAAAAAAAAAwECBAUGB//EADQRAAIBAgMEBwcFAQEAAAAAAAABAgMRBCExEkFR8AUTMmFxgbEUIpGhwdHhMzRCcvFSI//aAAwDAQACEQMRAD8AuqEIQAIQhAAhCEACEIQAIQisTiEqUvY6Io4szBQO87oANhIppHwhaOpzC2PaRzVoSP4myU9xkfxXhV3+84Xd0vdv/hVfxi3Vgt4p1oLeWXCVDd4TscT4teHUfNuT6y/4RB8JGkfSp/kj85Xr4FfaYFywlOJ4S9Ij/LntpP4OJvYbwqYgfCYalunZsdPr2pKrwD2inyi1YSDYHwn4N91td9XXsh19ana/pko0ZpzC4n4C+pzx2Q2Td6HJh6peM4vRjI1Iy0Z0YQhLFwhCEACEIQAIQhAAhCEACEIQAIQhAAhCeE5bz2wA9nO0zp3DYNNvEWKmfkrxdvkqN57eEhmtnhGVM6sDsu3A3EZoPmx556zu7ZWeJxFlrmy12d23szEknvPN1RE6yXZM1TEKOUc/QnWnfCbfZmuEQVLw23AaztC+Sv8AVIRjcbbe23dY9jdLsWy7M+A6hFVVs7BVDMx3AAEk9gHGSDCao25BsTYlAPBT49h7EX8+6ZKlXK839jK5Snr+PsR2CjM5DeegcfVLM0XqZXuKYWyz499mwv8ALHEd0kuE1dtQZcrTUPRqoGXrP5SE5S7MX6etr+RdUZPn/Cm6tEYl/Jw956+RfL15ZTYGreN/y9v8MuT/ANATzrb2/wBTIepQJidA4fot/mv+cnYqcF8fwW9nfP8AhTNmgMYvHD391bH6gZo30PX5aOnylK/XLxfQlXmvcvZY345xFmirBuTENl0OiuD9Uq+sW6/g19bEOhzzYpKeDp6N46paukNXlbPlMLTZ8apjU/aeGZ75GcbqlUTlTa1bf4dy5epwPwMr1sb2eXiUdNmroXXnHYbIcpyyDzLc23dT+UPWR1SxdXtfcJi8kc8had2y5Gyx6Fs4HsOR6pUWktFX4Y5XVsvQ3FT2MNx7OM0jNEKsokxrThk/nzc+lYSldV9eMTg8kszupG7YY+Mg+Ix+yd3RlLb0NpejGVcrQ4ZeBHBlPosvMf0JqhUUtDbTqxnpqb8IQjBgQhCABCEIAEIQgAQhMbHCgsxAABYknIADeSTzCAGGJxCVI1ljKqKCzMTkABxJMp7XTXWzGk007SYfhlwa3rfoXoX19AXrzra2Os5OokYdD4o4Gwj/AKjDo6BzcTv4RUDPcOwTJUq3yWhhrVtr3Y6ep5O/ofVp7VFtzclSeBI8d+pF5+3652tW9VtllNtfKXt4yU+ag9Ow/h9Z4WTovQwqPKWnlLfSI8VepBzDr4zOlKo7Q83uX35u0RTouWvP18vicHQWrBVfe09zoeLEBr7B1k+R+HRJNgdFUUb60G1zu3jMfpHf6puM8SzzTCjCnnq+L1/Hka4wURjPFM8wZ4pnkymTczZ4tni2eLZ4qUyLjGeJZ5gzxTPEymVuZs8RiFVxk4DDoIzgzxTPEymUZo2YEqCKiCh3GqzxkI6N+8SJY7Vym/NsKeTs56WbxWPxG5uw+yTZnkOmKriHQcdnTPLdu+Amdlbnn07iHYih62KWKysu4gjIibWh9LX4S0W0PstwI4qw9F15x+hkZMMQtWKQV4ncw3V3AeMnU3pL+usQ/S2i7cLZydo61YeS6+kp/WU6FDERqragxTVs0XTqprRTpCvNfFsXLlayd6/GB85DzH15TvT5z0bj7cNat1LFXU5g8x6VI51POJeWqmsNePo5RfFdcltTPejdXSp4g/iDOjSq7WT1NtGtt5PU7UIQjh4QhCABCEIAEq7woa0bbHA0t4qn9oYec3EVZ9A4nryHMZMddtP+4cKzqRyr+90j4xG9suhRv7chzyiySTmSSTvJJzJJ4knnMz15291GXEVLe6vM8k91S1daso5QHEONqtSN1Kc9r9B//OM5Wp+iQx902LtKrBKU/wASzm7gfb2S29D4HkEJYhrX8a1uvmUfFHATHbblsLzf08X6Z62FUad3fn/eA3Rej0w6ZLmzNvdz5TnpPQOgc02meLZ4tnmtWitmKyNiyVkZs8UzzFni2aLlMgzZ4lmnjNFM0TKZVsyZppYrHKhAPf1ROkdIBPFXyvq/3nBsuz4y1OG3m9CYxvqSflMxmOEwZpwMFpPkzk3kn2dYnX5QEZg5g7xMtZOm7MpJWMmaKZ54zRbNMsqhQwxduSMeo/VI1lOzpOzxMuk5fjOPlOdiZ3khM9TGbQ5O6v3PiPIO9H86puZh1dImtCLp1JU5bUSqdiK6V0dZhrTVYN43gjgyngw6j+cfq9pqzBYhbq9+Xiuue50PFT9YPMQJKsRhBjKeQOXKoC2HY8/pVE9By/WUgjqQSCCCCQQeII3EHrno6FZVYqcf8ZDVndH0Vo3HV4ipLqjtI67Sn6wRzEHMEcxBmzKm8FmsPJXHB2HxLTnVn5tuXk9QYD1gdMtmdSE9pXOhTqbcbhCEJcYEITia5aV9yYK21Tk+zydfy38VT3ZlvoyG7K7IbSV2VX4QdNe68a2yc66c6a+g5H3xu9h6lWcTReBbEXJSnFzln0DizdwBM1AJNNSNHkVNaPLvbkKj0Ln74/sy+jObUqWTk+e45ie3K755yRN9WcCmYsUZVVA1Ycdm57Osk7s+2SBniKa1rRUXcqgKOwQZ5eC6uNt+/wAd/wBl4G+KsjJnmDPFs0WWlZTC5mzTBmmBaYFoiVQi5kzTm6T0iK/FXyvq/wB4vSmkhWNlfK+z19sjlt+e8mMo0tr3paExjvY22/PeTNay2JstmvZbNtxg57ZtaN0vyR2X3of6esdXVOPZbNZ7YupBTjsyIeasWDygIzBBB3gjgRMGaQ/Q+nOROw+ZrPrU9I6ukfoyhrhs7QIIIzBHA58J5/FU5UZWem5mecbPM1Mc+bZdE0yJsMJgVnKlPadzOxBE8jCJiRLJlTFWIIIORBzB6xNHXHBBguMQZCw7FwHm2geV2MPq65vzZwNa2q+Gfybl2QfRdd6N3H8JuwNbq6lno8vsSlfLnuIAjlSGUkEEMCOIIOYI6wZfuq2mBjMJXfu2iNmwdFi7nHZnvHURKDtrZGKMMmUlWHQQciPWJPfBFpXYuswrHdYvKp8tNzDtK5H/AE56WjK0rcRmHnaVuJasIQmw3hKz8MWkN9GGB4Br2HbmlZ+9lmSjvCJi+V0ld0Js0r2Ioz/qLRNd2hYRiHaFuJHFUkgAZkkADpJ3AS4tX8EK3CDycPUtQ63YZu3b+crXVHDCzG1A8FJtP0AWHtAlp6D+B2zxsZrD3nIewCc6bTnFefwtb5tMz0VnfnI6bPMC0WXmBaTKZouZlpgWmBaYFpnlUIMy05eltKCobK73P9PWevqmGl9KiobK73P9PWevqkWtvJJJOZO8xtCjt+9LT1LxjfNjrbyTmTvO8zWstiLLZrPbN7YwfZdNay2KstmtZdIbAfZbNay2JstmrZbKkGw9s2dDayGl+TfM1Z9pQnzh1dI7+3h4i/mE1YmtTjVg4TWTIaTVmW0rBgGUggjMEHMEHgRPSJAtWtYDhzydmZqJ7ShPOOrpHeOueqwYAqQQRmCDmCDwIM8tisLLDz2XpufHnnIyzg4mBEURNgiYMIhMWzXInisQQRuIOY7RwjGEWZdFDla7YcDEC5Rkt6Lb9LyXHsB75zNB6Q9zYqm/gK7FZvkcHHepYd8kestW3gUfnptKfRtGf2gshpnqaFTbpxl3BJ2d148+Z9KwnJ1UxZuwOHsJzJqQMfjKNlvapnWnWTurnTTvmAnzvpi7lMTc/pW2v/E7H8Z9D55T5rRsxn07/XM+I3eZlxT7K8STajpk+Is9GllHa5GX2TLJwo2a0XoVR6gJXWpo94xZ6qF9btLELTmTl/6vwXzbK0tOeL+xmWnhaKLTEtEyqDRhac7TOONNe0vEnZHVmCc/ZNwtOHrY+VK/OD7DRdJqVSKelwWpHrrySSTmTvJmq9sTZbEWWzttjxr2xIYsQqgkk5ADiSeaJDFiFUEknIAcSTzCTjV3QYw427MjaRv6EB80dfSf0ceMxkMNDaeu5c7irdiCYhipKniCVPaDkZqWWzPSlvv1nzj/AGzOc9s0J3SZI6y2YXo4RXKnZfMK3MSu4jt6pqs+csLVDA136O5O1c1ayztBz3EHmI6ZkxmK9ngptXV0n4Z6d5EnYruE6en9CWYOzZbeh+DfLcw6D0MOicyaKdSNSKnB3TJTCSbUzSti2rhz4yPtbO/yCFLbuo5cO/pzjM62qf77T2v928RjIxlQntK9k35pZFZq6ZZBEWwjmEwYTySZjaNdhFsJsERLCMRVnuITbweKToRLR/pttSCSwcMudWIXpw932DK9no+j3egvP1ZEtEXP4LLtrRyr6Flqettv++S6QbwQt+xWjovPtrrk5ncp9hHQpdiIZZifNKLkAOgZT6WWfOek6di+1PQtsT+FyPwicRu8zPiv4+f0JFqcc6MWPmD/AFNO/hNJ2LuPjDr4+uR3UZ8ziK/Sp2x/psP/ALTqLPN9JSlCqpRe70Eq6S53skFOPRufI9B3TYzkdWOqcjgSO+Y/bH/JDFM7W1OBrk+VC/OD7DzfTEt1Huke19xhXDIch8Mo4/8AbsjcLiIyrw8RkXmiN2WxIYsQqgkk5AAZkk8wnPTGO5CqmbE5ADeSTwAGUsTVfQXudeUtANxHaEB8wdfSf0e3jMbDDQu829Fx/A5uw/VvQIw45SzI2kdyA+aOvpP6PczmImQE8diMVOrJzm8+dBbzKV0nZ7/b87b94ZpkzY0l8Pb87b94Zrz3FPsR8F6DUEs/wfj9hX5dn1ysJaXg9H7Cvzln2pyum/2y/svRlZ6HX0jgK76zVauan1g8xB5iJVOsGhLMHZstvQ/BvluYdB6GHOJcJE1NJYCu+s1Wrmp9YPMQeYicXAY+WGnZ5xeq+q7/AFKJ2KWnX1S/fae1/u3i9P6Eswdmy29D8G+W5h0HoYc4jNUf36ntf7t56evUjUws5wd04y9GXeaZZjCKYR7CKYTyKMrEsIthGtFNGIoxuFOVeIPRh7vsGV5J/e2zhMU3/aFf8xtmQCek6O/RXn6srLRFt+CBf2O09N5HqrT85OpEPBVTs6ODenbY/qIT+yS+d2n2Eb6XYj4BKL1/wvJaSxAy3MwtHXyihif4i3ql6SrvDBgMracQBudDSx60O0vrDt/DKV1eNxeJV4X4EX1MxATG1g8H2qj9NSB/VsyRshUlTxBIPccpA6bSjK6+UpDr2qcx7RLHx7K7Lcnk2otq943jtznnulad4Rnw+pljmhCxqxSxqzgMuhyyN6/1lsPUqgknEKAAMySa7MgBJIsZsA5EgHI5jdwORGY6NxI75FKr1VSM7aO4yLs7nB1S1aGGHKWZG4jtFYPmL19J7u2TqJiojFEVXrTqzc5u7Ze56BM1E8URqiZZPJlkii9J/D3fO2/eNNabOk/3i75277xprT6HS/Tj4L0GBLU8HY/YF+cs+1KrlreDkfsC/Ls+1OV05+2X9l6MiRISJgwjmEwYTyaYs0NJYCu+s1Wrmp9YPMwPMRIFo/QtmE0lSrb1JfYfLcw5N93Uw5xLIYRFiA5ZgHI5jdwORGY6NxPrm/DYydKE4fxkmreKtdc5kXsLYRLRzRTRURQhpgYxophGoozV1ks2MAF57rh/DWM/tZSEyTa83+/JQOFFYU/LfJn9mzOHorAnEX1UDP3x1r3cwY5Me4ZnunrcPT2KUY9wuetl4c+ZeOpmF5HR+GQjI8krkdBs98PtYztTxVAGQ3Abh2DhPZ10rKx00rKwSO6/aK91YC1VGb1+/wBe7ftV5kgdZUuO+SKEGrqzCSUk0z5rk11VxPLYRqT5dBLr11WHxh3Nn6xONrnoX3HjLKwMq299q6NhifF+ic17h0zR0FpI4W9LRvA8Vx6SNuYfj2gTlV6W3CUJHM7MrPzJoscsyxNQVgUOaMA9ZHAq28TBZ5GpFwk4vVDVwHLGrFLGrM0hiHLGrFLGrFMuhqiNQRaxqRM9GMRQ+k/3i75677xpqza0p+8XfP3feNNWfRaX6cfBehY9ls+Dgf8At6/OWfalTS2vBt/y9fnLPtTk9Pftl/ZejBkjYRTR7RJnkolGJaJaOaJeOiLYpopo1opo6JQS0bhCqbV1nkUqbW6/RHaTFNOXrnjeTrXBqfGOVt/bxRO7j6p0uj6PW1VwWb+gu9syJ4rENbY1j+U7F27WOfqk08E2i+UxT4hh4tK5Lu/6lgIGXYm3/EJB5e+pWhfceDSthlY3vtvy2yzH0QFX6M9ZRjeXgFCG1O/A7sIQmw6AQhCAEV8Ier/uzC7VYzupzsry4svn194AI61EpQGfSsqHwk6s+5rTiqh7za3jgDdXYePYrcR15jomavD+S553mTE0/wCa8xOp+kxYnuOw797Ydj08WrPUeI7+qdfZIORGRG4iVwpIIIJBG8EHIgjgQeYywdB6VGOTJshiUHjDhyqjzx8Yc4/Q4PSODdRdZDXf3iYO+RtqY1YhY1TPNsajYUxyzXUxqmJkMRsKY5DNdTGo0RNZDEUVpT94u+fu+8aa0mWN1Bxz22OrYXJrLLBnbZnkzkjP3vjkYn/h3j/Swn86z/xT28Ok8JGEU6i0XH7FiJy2vBt/y9fnLPtSI/8ADvH+lhP51n/ik61R0ZZhMKKbTWWDu3ikkZMcxvIH1Tm9L4zD16CjTmm9pPfwZB13MU0zYxTGediirFuYpzGMYgmOiLZi0QxjGMMkVGuubZqTyjzseZV6SZpo05VJKMdRbF34pMLUcTYAT5NKnz7Ob6I4nsldYi9rHZ3JLMSzHpJ4ze09pd8XbtsNlQNmtOZF6O085/IROitHW4q5KKRmznLqUeczdCgb/wDeetwuHVGCgtfqJk7uyJN4NNX/AHTieXce9UEN1NbxRe7yj9HplxzQ0HoqvB0JRVwUbyeLMd7Oesn8uab861OGyrG+lT2I2CEIS4wIQhAAicZhUuraq1QyOCrKeBBjoQAojW/VqzR92yc2qck1WdI9Buhx7eI5wOJTcyMHRirKdpSDkQRzifQ+lNHVYmpqblDI3Ec4PMwPMRzGUrrbqpdo99+b0scq7cvUr+i/sPNzgY6tJxd1oYK1FxzWnoSLQum68bkj7KYj1Ld1jobq/Q3ipU5EEEcRKwEluhtbtwrxgZ1G5bR8IvyvTHt7ZxMb0aqt508nvW5kRqcSSqY5Wi0rDJylTLZWeDKc+4jiDMVaecrUp03szVmOvY2laMVprK0zDTM4lrm0Gnu3EBp7tyuyW2hpeYFpiWiy0FENozZotmnjNFM0YkUuesYljG1VM5yUE/UO0zmaU0/hsLmq7N9w5gfe0Pxm849Q9k3YXB1K791ZcdxRtam7e1dNfLYhtmvzR51h9FBz/rtkF0/pyzFuMxsVrurrHBR0npbrmtpLSNuJs5S5yzcB0KOhRzCKwmEsusWqpGd2OSqBvP5DrO4T0+FwkKEbRzfEROd8kYUUvY6pWpZ2IVVAzJJ4AS69SNVlwFWb5NfYByjDgo4itT0DnPOe7JWpOpyYFeUs2XxDDJm5kB4on4tz9Q3SVzq0qWzmzVQo7PvS1CEIR5pCEIQAIQhAAhCEACKxOHSxGrsVWRhssrDMEdBBjYQAqnWzwdWVZ24INZXxNWedi/IPnjq8r5UgJGRIO4g5Ec4I4g9c+lJwNYdUcJjs2sXYs5rUyDfS5nHb3ZTPOhfOJlqYe+cCksBj7sO23TYyNz5Hceog7mHbJXgddEbdiqd/+JVuPaUO49ufdNfTuoGNw2bVry9Y86sHbA66+P8ADtSKEZEg7iNxHOD0Ec0x1aEZrZqR+Jm9+Ds8i0MHjMNf8BiKiT5reI/8LcZuNhLF4oe4Z/VKiM3MJpPEVfBXWoOhbGA9WeU5lToejLOLa57y6rcUWYSRxzENuQWrXDHr/wBcn5VdZ9uznHDXfG9NX8lZjfQbvlP5fkv1sSZ8pGLU54KT65Bn11x54WKvyak/EGaWJ1hxtnl4i7ufZ9iZS0Og/wDqfyt9yHWiWLiKxWM7rKqh8dwPUOecXG604OrdWHxDdmxXn2nee4GQBiScySSeJJzPrnk30ui8PTzau+/mxR1XuR2tLazYnEjYLBK/8OsbK5dfO3ecuqcadLQ2r+Lxh/Z6XYc7nxax9M7u4Znqli6veDSmrJ8Y3LNx2FzFQ7ed/YOozpwpN9lZERhOpn8yBat6sYnHt70uzWDk1rA7A6QPTbqHflLg1b1aw+ATZqGbsPHsby26vir8Ue0752Kq1VQqgKoGQAAAAHMAOAmU1wpKPibKdGMM9WEIQjBwQhCABCEIAEIQgAQhCABCEIAEIQgATnaU0HhcV+8U1ueG0VycdjjJh650YQavqQ1fIgWkfBdhmzNF1tR5gwFij6m9pkfxfgxxq/B2YewfKZD6ipHtluwinRg9wp0Kb3fAo67UXSa//GJ61tqP92cQdT9I/wCUu9S/nL4hK9RHiynsseLKKTUvSR4YWzvasfWwm9hvBxpF/KWmv5dwP2A0ueElUI95Kw0O8rTA+CrnvxXdXX/e5/tko0XqPo/D5EUixhl41rbfDn2T4oPYJI4S6pxWiGRowjojwDIZDgNwnsIS4wIQhAAhCEACEIQAIQhAAhCEACEIQAIQhAAhCEACEIQAIQhAAhCEACEIQAIQhAAhCEACEIQAIQhAAhCEACEIQA//2Q=="
              alt=""
              className="h-10 w-10 rounded-full filter grayscale hover:grayscale-0 cursor-pointer animate-bounce"
            />
          </div>
        </footer>
      </Link> */}
    </div>
  );
};

export default Home;

export const getStaticProps:GetStaticProps<Props> = async () => {
 
  const experiences: Experience[] = await fetchExperiences();
  const skills: Skill[] = await fetchSkills();
  const projects: Project[] = await fetchProjects();
  const socials: Social[] = await fetchSocials();
  const heroInfo: HeroInfo = await fetchHeroInfo();
  const aboutInfo: AboutInfo = await fetchAboutInfo();
  const contactsInfo: ContactsInfo = await fetchContactsInfo();
 
  return{
    props: {
     
      experiences,
      skills,
      projects,
      socials,
      heroInfo,
      aboutInfo,
      contactsInfo
    },

    revalidate: 10,
  }
  
}
